---

- name: update system
  apt: update_cache=yes

- name: install needed soft
  apt: name={{ item }} state=installed
  with_items:
    - nginx
    - supervisor
    - mysql-server
    - python-mysqldb
    - python
    - libpq-dev
    - python-mysqldb
    - libmysqlclient-dev
  notify:
    - restart nginx

- name: copy nginx config
  template: src=tt1.cupermind.com.conf.j2 dest=/etc/nginx/sites-available/tt1.cupermind.com.conf owner=root group=root mode=0644

- name: create symlink for config
  file: src=/etc/nginx/sites-available/tt1.cupermind.com.conf dest=/etc/nginx/sites-enabled/tt1.cupermind.com.conf state=link
  notify:
    - restart nginx

- name: copy supervisor config
  template: src=django.conf.j2 dest=/etc/supervisor/conf.d/django.conf owner=root group=root mode=0644
  notify:
    - restart supervisor

- name: restart supervisor
  service: name=supervisor state=restarted enabled=true

- name: add system user
  user: name={{user_name}} shell=/bin/bash home={{home_dir}}

- name: start mysql
  service: name=mysql state=restarted enabled=true

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "localhost"
    password: "123456"
    login_user: root
    login_password: "123456"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: create MySQL user
  mysql_user:
    name: "{{ user_name }}"
    host: "localhost"
    password: "{{ user_name }}"
    priv: "{{ user_name }}.*:ALL"
    login_user: root
    login_password: "123456"
    state: present

- name: drop database if exist
  mysql_db:
    name: "{{user_name}}"
    state: absent
    login_user: root
    login_password: "123456"

- name: create MySQL database
  mysql_db:
    name: "{{ user_name }}"
    collation: utf8_general_ci
    encoding: utf8
    login_user: root
    login_password: "123456"
    state: present